# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.
#
# NOTE: 
# Brian Parks has renamed the UnixHostDunio library to EpoxyDuino so at some
# point this will need ot be changed to:
# include ../../../../EpoxyDuino/UnixHostDuino.mk
#
APP_NAME := simpleSerialShellTest
ARDUINO_LIBS := AUnit SimpleSerialShell
CPPFLAGS += -Werror
include ../../../../EpoxyDuino/UnixHostDuino.mk
#(old) include ../../../../UnixHostDuino/UnixHostDuino.mk
