# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.
#

APP_NAME := simpleSerialShellTest
ARDUINO_LIBS := AUnit SimpleSerialShell
CPPFLAGS += -Werror
include ../../../../UnixHostDuino/UnixHostDuino.mk
