# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.
#
# NOTE: At the moment there is a dependency on V1.0.0 of the EpoxyDuino 
# project due to some confusion around end-of-line treatment.  
#
APP_NAME := CustomParserTest
ARDUINO_LIBS := AUnit SimpleSerialShell
CPPFLAGS += -Werror
include ../../../../EpoxyDuino/UnixHostDuino.mk
#(old) include ../../../../UnixHostDuino/UnixHostDuino.mk
