# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.
#
APP_NAME := HelpTest
ARDUINO_LIBS := AUnit SimpleSerialShell
CPPFLAGS += -Werror
include ../../../../EpoxyDuino/UnixHostDuino.mk
