name: Arduino SimpleSerialShell Lib build permutation check

# See https://learn.adafruit.com/the-well-automated-arduino-library/doxygen

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: test platforms
      run: python3 ci/build_platform.py main_platforms

    # Make sure:
    #    there is a "gh-pages" branch
    #    github repository has a secret GH_REPO_TOKEN with repo access
    #        (used to push generated docs back onto github)
    #
    # NOTE: at this time I don't think doxygen is worth it for this
    #       library. Overkill for a "simple shell"?
    #
    #       See the README.md for how to use.
    #
    #- name: doxygen
    #  env:
    #    GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
    #    PRETTYNAME : "SimpleSerialShell Library"
    #  run: bash ci/doxy_gen_and_deploy.sh
